### PR TITLE
Upgrade for compatibility with .NET8

### PR DESCRIPTION
**Pull request by SergeiPavlov**

### CODE REVIEW

**Review by shuruev — COMMENTED** [review]
I suggest we wait until .NET 8 is released, and then properly migrate to NSwag 14.0.x version.

Here is an example of such a "migration" PR describing all the steps: https://github.com/servicetitan/NSwag/pull/45

Or what do you think? ++ @avimra

**Comment by shuruev** [comment]
Otherwise this PR would create more noise and increases the effort to maintain this fork. Basically because here you'd provide your own way to add .NET 8 in these files, while the author of NSwag already did that in his 14.0.x branch.

**Comment by SergeiPavlov** [comment]
> If you just wanted to "try" using .NET 8 with the existing code, then I think this PR changes more than it should.

I discovered it is not enough for API-client-generator
Because structure of `NSwag` classes is changed.

API-client-generator cannot load assemblies built with .NET8

**Comment by SergeiPavlov** [comment]
We patched version constraints instead

**Pull request closed without merging**
